### ISSUE TITLE
Android Monetize documentation fails to mention required 3rd party dependency 

### ISSUE THREAD

**Issue by mvberg** [sharethrough/Android-SDK#47]
The latest "Monetize Sharethrough Android SDK" depends on [Picasso from Square](https://github.com/square/picasso), however the documentation for said SDK mentions this nowhere - and if it is not explicitly added to the class path, your project will blow up with ClassNotFoundErrors.

Can you guys please add this to the documentation in hopes of aiding future devs?

Documenation: http://developers.sharethrough.com/android/#requirements
Required dependency: http://square.github.io/picasso/
Exception if missing: https://gist.github.com/mvberg/c32952d733b724d37d762986eab3da44#file-java-L12

TY.

**Comment by dshei** [comment]
Thanks! We will add it to our developers doc

**Comment by mvberg** [comment]
@dshei; Hi; 

Same now for your v4.0 release

You are missing a new dep from your docs

com.android.volley:volley:1.0.0

https://github.com/sharethrough/Android-SDK/blob/master/build.gradle#L179
